name: itargs
description: testing task for itargs company.

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0


  # State Management
  flutter_riverpod: any
  riverpod: ^2.2.0


  #local
  shared_preferences: any

  #remote
  dio: ^5.0.1
  json_annotation: ^4.5.0

  #localization
  easy_localization: ^3.0.0

  #routing
  go_router: ^8.0.1

  #utils
  just_audio_cache: ^0.1.2


  #testing
  mockito: ^5.4.2

dev_dependencies:
  build_runner: ^2.4.6

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/fonts/
     - assets/icons/Home/
     - assets/icons/Like/
     - assets/icons/More/
     - assets/icons/Play/


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
